install.packages(RSQLite)
library(RSQLite)
con <- dbConnect(SQLite(), dbname = "powerconsumption")
dbWriteTable(con, name="powerconsumption", value="household_power_consumption.txt",  row.names=FALSE, header=TRUE, sep = ";")
power <- dbGetQuery(con, "SELECT * FROM powerconsumption WHERE Date='1/2/2007' OR Date='2/2/2007'")
dbDisconnect(con)
Dates <- as.Date(power$Date, format="%d/%m/%Y")
Times <- power$Time
power$DateTime <- as.POSIXct(paste(Dates, Times), format="%Y-%m-%d %H:%M:%S")
png(filename="plot3.png")
plot(power$DateTime, power$Sub_metering_1, xlab="", ylab="Energy sub metering", type="n")
lines(power$DateTime, power$Sub_metering_1)
lines(power$DateTime, power$Sub_metering_2, col="red")
lines(power$DateTime, power$Sub_metering_3, col="blue")
legend("topright", lwd=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
